JournalFame = {"4" : 1200,
               "5" : 2400,
               "6" : 4800,
               "7" : 9600,
               "8" : 19200}

FameGenerated = {"4": {"2Hweapon":720, "1Hweapon":540, "BigArmor":360, "SmallArmor":180},
                 "5": {"2Hweapon":2880, "1Hweapon":2160, "BigArmor":1440, "SmallArmor":720},
                 "6": {"2Hweapon":8640, "1Hweapon":6480, "BigArmor":4320, "SmallArmor":2160},
                 "7": {"2Hweapon":20640, "1Hweapon":15480, "BigArmor":10320, "SmallArmor":5160},
                 "8": {"2Hweapon":44640, "1Hweapon":33480, "BigArmor":22320, "SmallArmor":11160}}

clothCost = {"BattleAxe" : 0,
             "Halberd" : 0,
             "Great_Axe" : 0,
             "Boots" : 0,
             "Shield" : 0,
             "1H_Crossbow" : 0,
             "2H_Crossbow" : 0,
             "Armor" : 0,
             "1H_Hammer" : 0,
             "2H_Hammer" : 12,
             "Helmet" : 0,
             "1H_Mace" : 8,
             "2H_Mace" : 12,
             "1H_Sword" : 0,
             "2H_Sword" : 0,
             "Robe" : 16,
             "Sandals" : 8,
             "Cowl" : 8,
             "1H_Damage_Staff" : 0,
             "2H_Damage_Staff" : 0,
             "1H_Holy_Staff" : 8,
             "2H_Holy_Staff" : 12,
             "SpellTome" : 4,
             "Torch" : 4,
             "1H_Nature_Staff" : 8,
             "2H_Nature_staff" : 12,
             "1H_Dagger" : 0,
             "2H_Dagger" : 0,
             "Claws" : 0,
             "Staff" : 0,
             "1H_Spear" : 0,
             "Pike" : 0,
             "Glaive" : 0,
             "Jacket" : 0,
             "Boots" : 0,
             "Hood" : 0}

metalCost = {"BattleAxe" : 16,
             "Halberd" : 12,
             "Great_Axe" : 20,
             "Boots" : 8,
             "Shield" : 4,
             "1H_Crossbow" : 8,
             "2H_Crossbow" : 12,
             "Armor" : 16,
             "1H_Hammer" : 24,
             "2H_Hammer" : 20,
             "Helmet" : 8,
             "1H_Mace" : 16,
             "2H_Mace" : 20,
             "1H_Sword" : 16,
             "2H_Sword" : 20,
             "Robe" : 0,
             "Sandals" : 0,
             "Cowl" : 0,
             "1H_Damage_Staff" : 8,
             "2H_Damage_Staff" : 12,
             "1H_Holy_Staff" : 0,
             "2H_Holy_Staff" : 0,
             "SpellTome" : 0,
             "Torch" : 0,
             "1H_Nature_Staff" : 0,
             "2H_Nature_staff" : 0,
             "1H_Dagger" : 12,
             "2H_Dagger" : 16,
             "Claws" : 12,
             "Staff" : 12,
             "1H_Spear" : 8,
             "Pike" : 12,
             "Glaive" : 20,
             "Jacket" : 0,
             "Boots" : 0,
             "Hood" : 0}

woodCost = {"BattleAxe" : 8,
             "Halberd" : 20,
             "Great_Axe" : 12,
             "Boots" : 0,
             "Shield" : 4,
             "1H_Crossbow" : 16,
             "2H_Crossbow" : 20,
             "Armor" : 0,
             "1H_Hammer" : 0,
             "2H_Hammer" : 0,
             "Helmet" : 0,
             "1H_Mace" : 0,
             "2H_Mace" : 0,
             "1H_Sword" : 0,
             "2H_Sword" : 0,
             "Robe" : 0,
             "Sandals" : 0,
             "Cowl" : 0,
             "1H_Damage_Staff" : 16,
             "2H_Damage_Staff" : 20,
             "1H_Holy_Staff" : 16,
             "2H_Holy_Staff" : 20,
             "SpellTome" : 0,
             "Torch" : 4,
             "1H_Nature_Staff" : 16,
             "2H_Nature_staff" : 20,
             "1H_Dagger" : 0,
             "2H_Dagger" : 0,
             "Claws" : 0,
             "Staff" : 0,
             "1H_Spear" : 16,
             "Pike" : 20,
             "Glaive" : 12,
             "Jacket" : 0,
             "Boots" : 0,
             "Hood" : 0}

leatherCost = {"BattleAxe" : 0,
               "Halberd" : 0,
               "Great_Axe" : 0,
               "Boots" : 0,
               "Shield" : 0,
               "1H_Crossbow" : 0,
               "2H_Crossbow" : 0,
               "Armor" : 0,
               "1H_Hammer" : 0,
               "2H_Hammer" : 0,
               "Helmet" : 0,
               "1H_Mace" : 0,
               "2H_Mace" : 0,
               "1H_Sword" : 8,
               "2H_Sword" : 12,
               "Robe" : 0,
               "Sandals" : 0,
               "Cowl" : 0,
               "1H_Damage_Staff" : 0,
               "2H_Damage_Staff" : 0,
               "1H_Holy_Staff" : 0,
               "2H_Holy_Staff" : 0,
               "SpellTome" : 4,
               "Torch" : 0,
               "1H_Nature_Staff" : 0,
               "2H_Nature_staff" : 0,
               "1H_Dagger" : 12,
               "2H_Dagger" : 16,
               "Claws" : 20,
               "Staff" : 20,
               "1H_Spear" : 0,
               "Pike" : 0,
               "Glaive" : 0,
               "Jacket" : 16,
               "Boots" : 8,
               "Hood" : 8}

craftedItems = {"BattleAxe" : 0,
                "Halberd" : 0,
                "Great_Axe" : 0,
                "Boots" : 0,
                "Shield" : 0,
                "1H_Crossbow" : 0,
                "2H_Crossbow" : 0,
                "Armor" : 0,
                "1H_Hammer" : 0,
                "2H_Hammer" : 0,
                "Helmet" : 0,
                "1H_Mace" : 0,
                "2H_Mace" : 0,
                "1H_Sword" : 0,
                "2H_Sword" : 0,
                "Robe" : 0,
                "Sandals" : 0,
                "Cowl" : 0,
                "1H_Damage_Staff" : 0,
                "2H_Damage_Staff" : 0,
                "1H_Holy_Staff" : 0,
                "2H_Holy_Staff" : 0,
                "SpellTome" : 0,
                "Torch" : 0,
                "1H_Nature_Staff" : 0,
                "2H_Nature_staff" : 0,
                "1H_Dagger" : 0,
                "2H_Dagger" : 0,
                "Claws" : 0,
                "Staff" : 0,
                "1H_Spear" : 0,
                "Pike" : 0,
                "Glaive" : 0,
                "Jacket" : 0,
                "Boots" : 0,
                "Hood" : 0}

RRR = {"N" : 0.248,
       "Y" : 0.479}

focusMessage = {"N" : "Focus was not used",
                "Y" : "Focus was used"}